name: Release lndata-go

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-lndata-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: olegtarasov/get-tag@v2.1.1
        id: tagName

      - name: Release new lndata-go version
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          tag_name: ${{ steps.tagName.outputs.tag }}
          repository: c13n-io/lndata-go